services:
  - type: web
    name: montanitaadopta-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: API_URL
        value: https://montanitaadopta.onrender.com/adoptme/api/v1/
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "true"