"""Descripción del cambio

Revision ID: 1449ca9f570f
Revises: be5f52e6d595
Create Date: 2025-03-28 18:50:27.958617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1449ca9f570f'
down_revision: Union[str, None] = 'be5f52e6d595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('success_stories', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('success_stories', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('success_stories', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('success_stories', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('success_stories', 'image_url')
    op.drop_column('success_stories', 'image_path')
    op.drop_column('success_stories', 'email')
    op.drop_column('success_stories', 'name')
    # ### end Alembic commands ###
