"""Agregar tabla veterinary_services

Revision ID: 65a069eef7f5
Revises: 1449ca9f570f
Create Date: 2025-03-28 18:54:33.731501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a069eef7f5'
down_revision: Union[str, None] = '1449ca9f570f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
