"""inicial

Revision ID: dc16fd3ca052
Revises: 
Create Date: 2025-03-09 21:41:18.028537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc16fd3ca052'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adopciones')
    op.create_index(op.f('ix_contacto_id'), 'contacto', ['id'], unique=False)
    op.create_index(op.f('ix_mascotas_id'), 'mascotas', ['id'], unique=False)
    op.create_index(op.f('ix_success_stories_id'), 'success_stories', ['id'], unique=False)
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('usuarios', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
    op.alter_column('usuarios', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index(op.f('ix_success_stories_id'), table_name='success_stories')
    op.drop_index(op.f('ix_mascotas_id'), table_name='mascotas')
    op.drop_index(op.f('ix_contacto_id'), table_name='contacto')
    op.create_table('adopciones',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mascota_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usuario_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('fecha_adopcion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('estado', mysql.VARCHAR(length=20), server_default=sa.text("'pendiente'"), nullable=False),
    sa.Column('comentarios', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['mascota_id'], ['mascotas.id'], name='adopciones_ibfk_1'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='adopciones_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
