"""Actualización de tablas

Revision ID: f020e4d0a330
Revises: 6e406aafa815
Create Date: 2025-03-11 19:04:06.586600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f020e4d0a330'
down_revision: Union[str, None] = '6e406aafa815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('codigo_postal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'codigo_postal')
    # ### end Alembic commands ###
