"""Actualización de tablas

Revision ID: f2ee89648532
Revises: f020e4d0a330
Create Date: 2025-03-12 19:05:12.447278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f2ee89648532'
down_revision: Union[str, None] = 'f020e4d0a330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mascotas', 'sexo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mascotas', sa.Column('sexo', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
